require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Package = require('../models/package');

const packages = [
    // ── Domestic Packages ──
    {
        title: 'Enchanting Kerala Backwaters',
        description: 'Explore the serene backwaters of Kerala with houseboat stays and palm-fringed canals. A perfect escape into nature.',
        type: 'domestic',
        region: 'South India',
        destination: 'Kerala',
        country: 'India',
        duration: { days: 6, nights: 5 },
        price: 24999, pricePerPerson: 24999,
        highlights: ['Houseboat Stay in Alleppey', 'Munnar Tea Plantations', 'Kathakali Dance Show'],
        inclusions: ['Accommodation', 'Meals', 'Transportation', 'Guide'],
        exclusions: ['Flights', 'Personal Expenses'],
        category: ['Nature', 'Romantic', 'Honeymoon', 'Wellness and Spa', 'Customized Holidays'],
        theme: ['Domestic'],
        bestMonths: ['JAN', 'FEB', 'MAR', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'],
        featured: true, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800']
    },
    {
        title: 'Royal Rajasthan Explorer',
        description: 'Journey through the land of kings – Jaipur, Jodhpur, Udaipur & Jaisalmer with palace stays and camel safaris in the Thar desert.',
        type: 'domestic',
        region: 'North India',
        destination: 'Rajasthan',
        country: 'India',
        duration: { days: 8, nights: 7 },
        price: 32999, pricePerPerson: 32999,
        highlights: ['Amber Fort Elephant Ride', 'Desert Safari in Jaisalmer', 'Lake Palace Udaipur'],
        inclusions: ['Heritage Hotel Stays', 'Breakfast', 'Transportation'],
        exclusions: ['Flights', 'Lunch'],
        category: ['Heritage', 'Family', 'Luxury', 'Fixed Departures'],
        theme: ['Domestic'],
        bestMonths: ['JAN', 'FEB', 'MAR', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'],
        featured: true, hotDeal: true,
        images: ['https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800']
    },
    {
        title: 'Goa Beach Paradise',
        description: 'Sun, sand and seafood! Experience the vibrance of Goa with beach parties, water sports and Portuguese heritage.',
        type: 'domestic',
        region: 'West India',
        destination: 'Goa',
        country: 'India',
        duration: { days: 5, nights: 4 },
        price: 15999, pricePerPerson: 15999,
        highlights: ['Water Sports at Calangute', 'Old Goa Churches', 'Dudhsagar Falls'],
        inclusions: ['Beach Resort Stay', 'Breakfast', 'Water Sports (1 session)'],
        exclusions: ['Flights', 'Meals'],
        category: ['Beach', 'Adventure', 'Friends', 'Customized Holidays'],
        theme: ['Domestic'],
        bestMonths: ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'OCT', 'NOV', 'DEC'],
        featured: false, hotDeal: true,
        images: ['https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800']
    },
    {
        title: 'Himalayan Adventure – Manali & Shimla',
        description: 'A magical mountain escape with snow sports, lush valleys, and charming colonial hill stations.',
        type: 'domestic',
        region: 'North India',
        destination: 'Himachal Pradesh',
        country: 'India',
        duration: { days: 7, nights: 6 },
        price: 19999, pricePerPerson: 19999,
        highlights: ['Rohtang Pass', 'Solang Valley Adventure', 'Mall Road Shimla'],
        inclusions: ['Hotel Stay', 'Meals', 'Volvo Transport'],
        exclusions: ['Flights to Delhi', 'Optional Activities'],
        category: ['Adventure', 'Nature', 'Family', 'Fixed Departures'],
        theme: ['Domestic'],
        bestMonths: ['MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT'],
        featured: true, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800']
    },
    {
        title: 'Andaman Island Getaway',
        description: 'Crystal clear waters, vibrant coral reefs and pristine beaches on the distant Andaman Islands. A tropical dream.',
        type: 'domestic',
        region: 'Island',
        destination: 'Andaman',
        country: 'India',
        duration: { days: 6, nights: 5 },
        price: 28999, pricePerPerson: 28999,
        highlights: ['Scuba Diving at Havelock', 'Radhanagar Beach', 'Cellular Jail'],
        inclusions: ['Resort Stay', 'Meals', 'Ferry Transfers'],
        exclusions: ['Flights', 'Personal Expenses'],
        category: ['Beach', 'Adventure', 'Honeymoon'],
        theme: ['Domestic'],
        bestMonths: ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'SEP', 'OCT', 'NOV', 'DEC'],
        featured: false, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1544550581-5f7ceaf7f992?w=800']
    },
    {
        title: 'Kashmir – Heaven on Earth',
        description: 'Explore the undisputed paradise of India with Shikara rides on Dal Lake, Gulmarg snow meadows and lush Pahalgam valleys.',
        type: 'domestic',
        region: 'North India',
        destination: 'Kashmir',
        country: 'India',
        duration: { days: 7, nights: 6 },
        price: 26999, pricePerPerson: 26999,
        highlights: ['Shikara Ride on Dal Lake', 'Gulmarg Gondola', 'Pahalgam Valley'],
        inclusions: ['Houseboat Stay', 'Meals', 'Transportation'],
        exclusions: ['Flights', 'Pony Rides'],
        category: ['Nature', 'Romantic', 'Honeymoon'],
        theme: ['Domestic'],
        bestMonths: ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'],
        featured: true, hotDeal: true,
        images: ['https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800']
    },
    {
        title: 'Simply Darjeeling & Gangtok',
        description: 'Discover the tea gardens of Darjeeling and the serene monasteries of Gangtok wrapped in misty Himalayan clouds.',
        type: 'domestic',
        region: 'East India',
        destination: 'Sikkim & Darjeeling',
        country: 'India',
        duration: { days: 6, nights: 5 },
        price: 22500, pricePerPerson: 22500,
        highlights: ['Tiger Hill Sunrise', 'Peace Pagoda', 'Nathu La Pass (Optional)'],
        inclusions: ['Hotel', 'Transport', 'Breakfast'],
        exclusions: ['Flights', 'Nathu La Permit'],
        category: ['Nature', 'Family', 'Heritage'],
        theme: ['Domestic'],
        bestMonths: ['MAR', 'APR', 'MAY', 'JUN', 'SEP', 'OCT', 'NOV'],
        featured: false, hotDeal: true,
        images: ['https://images.unsplash.com/photo-1544645398-963d8ce7b707?w=800']
    },
    {
        title: 'Majestic Meghalaya',
        description: 'Journey to the abode of clouds. Experience living root bridges, crystal clear rivers, and the wettest places on earth.',
        type: 'domestic',
        region: 'East India',
        destination: 'Meghalaya',
        country: 'India',
        duration: { days: 5, nights: 4 },
        price: 18500, pricePerPerson: 18500,
        highlights: ['Double Decker Root Bridge', 'Dawki River', 'Cherrapunji Waterfalls'],
        inclusions: ['Hotel', 'Local Transport', 'Breakfast'],
        exclusions: ['Flights', 'Entry Fees'],
        category: ['Adventure', 'Nature'],
        theme: ['Domestic'],
        bestMonths: ['MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV'],
        featured: false, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1627850991660-35ecb37803ba?w=800']
    },
    {
        title: 'Wildlife Odyssey - Ranthambore & Bandhavgarh',
        description: 'Thrilling tiger safaris deep in the jungles of Central India. Spot majestic Bengal tigers in their natural habitat.',
        type: 'domestic',
        region: 'Central India',
        destination: 'Madhya Pradesh',
        country: 'India',
        duration: { days: 5, nights: 4 },
        price: 29999, pricePerPerson: 29999,
        highlights: ['Jeep Safari in Ranthambore', 'Elephant Safari in Bandhavgarh', 'Nature Walks'],
        inclusions: ['Resort Stay', 'All Meals', '2 Safari Rides'],
        exclusions: ['Transport to Park', 'Camera Fees'],
        category: ['Adventure', 'Wildlife', 'Nature'],
        theme: ['Domestic'],
        bestMonths: ['JUN', 'JUL', 'AUG', 'SEP', 'OCT'],
        featured: true, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1582046755452-f47dc79de1a8?w=800']
    },
    {
        title: 'Spiritual Varanasi & Prayagraj',
        description: 'Experience the deep spiritual roots of India along the sacred Ganges river with mesmerizing evening aartis.',
        type: 'domestic',
        region: 'North India',
        destination: 'Uttar Pradesh',
        country: 'India',
        duration: { days: 4, nights: 3 },
        price: 12500, pricePerPerson: 12500,
        highlights: ['Ganga Aarti at Dashashwamedh', 'Morning Boat Ride', 'Sarnath Tour'],
        inclusions: ['Accommodation', 'Breakfast', 'Local Transport'],
        exclusions: ['Flights', 'Donations'],
        category: ['Heritage', 'Family'],
        theme: ['Domestic'],
        bestMonths: ['JAN', 'FEB', 'MAR', 'OCT', 'NOV', 'DEC'],
        featured: false, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=800']
    },

    // ── International Packages ──
    {
        title: 'Dubai & Abu Dhabi Explorer',
        description: 'Experience luxury and high-adrenaline adventure in the UAE – desert safaris, Burj Khalifa views, and futuristic theme parks.',
        type: 'international',
        region: 'Middle East',
        destination: 'Dubai',
        country: 'UAE',
        duration: { days: 6, nights: 5 },
        price: 54999, pricePerPerson: 54999,
        highlights: ['Burj Khalifa At The Top', 'Desert Safari with BBQ', 'Abu Dhabi Mosque'],
        inclusions: ['4-star Hotel', 'Breakfast', 'Desert Safari', 'City Tours'],
        exclusions: ['Flights', 'Visa', 'Theme Park Tickets'],
        category: ['Luxury', 'Family with Kids', 'Shopping', 'City Breaks', 'Customized Holidays'],
        theme: ['International'],
        bestMonths: ['NOV', 'DEC', 'JAN', 'FEB', 'MAR'],
        featured: true, hotDeal: true,
        images: ['https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800']
    },
    {
        title: 'Magical Thailand',
        description: 'Discover the vibrant culture, stunning temples, and beautiful beaches of Thailand.',
        type: 'international',
        region: 'Asia',
        destination: 'Thailand',
        country: 'Thailand',
        duration: { days: 7, nights: 6 },
        price: 39999, pricePerPerson: 39999,
        highlights: ['Grand Palace Bangkok', 'Phi Phi Islands Tour', 'Coral Island'],
        inclusions: ['Hotel Stay', 'Daily Breakfast', 'Island Tours'],
        exclusions: ['Flights', 'Visa', 'Optional Activities'],
        category: ['Beach', 'City Breaks', 'Shopping', 'Friends', 'Visa on Arrival', 'Fixed Departures'],
        theme: ['International'],
        bestMonths: ['NOV', 'DEC', 'JAN', 'FEB', 'MAR', 'APR'],
        featured: true, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1528181304800-259b08848526?w=800']
    },
    {
        title: 'Singapore & Malaysia Combo',
        description: 'Two spectacular countries in one trip – futuristic Gardens by the Bay, thrilling Universal Studios, and the soaring KL Twin Towers.',
        type: 'international',
        region: 'Asia',
        destination: 'Singapore & Malaysia',
        country: 'Singapore',
        duration: { days: 7, nights: 6 },
        price: 49999, pricePerPerson: 49999,
        highlights: ['Gardens by the Bay', 'Universal Studios', 'Petronas Twin Towers'],
        inclusions: ['4-star Hotels', 'Breakfast', 'City Tours', 'USS Ticket'],
        exclusions: ['Flights', 'Visa', 'Dining'],
        category: ['City Breaks', 'Family with Kids', 'Shopping', 'Theme Park', 'Customized Holidays'],
        theme: ['International'],
        bestMonths: ['FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG'],
        featured: false, hotDeal: true,
        images: ['https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800']
    },
    {
        title: 'Bali – Island of Gods',
        description: 'Find inner peace in Bali with its emerald rice terraces, ancient sea temples, and stunning trendy beach clubs.',
        type: 'international',
        region: 'Asia',
        destination: 'Bali',
        country: 'Indonesia',
        duration: { days: 6, nights: 5 },
        price: 42999, pricePerPerson: 42999,
        highlights: ['Ubud Rice Terraces', 'Tanah Lot Temple', 'Nusa Penida Trip'],
        inclusions: ['Villa Stay', 'Breakfast', 'Tours'],
        exclusions: ['Flights', 'Visa on Arrival'],
        category: ['Beach', 'Romantic', 'Honeymoon', 'Nature', 'Wellness and Spa', 'Visa Free', 'Fixed Departures'],
        theme: ['International'],
        bestMonths: ['APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP'],
        featured: true, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800']
    },
    {
        title: 'Maldives Luxury Escape',
        description: 'Dazzling overwater villas, crystal clear turquoise waters, and world-class diving or simply relaxing in ultimate luxury.',
        type: 'international',
        region: 'Island',
        destination: 'Maldives',
        country: 'Maldives',
        duration: { days: 5, nights: 4 },
        price: 79999, pricePerPerson: 79999,
        highlights: ['Overwater Villa Stay', 'Sunset Dolphin Cruise', 'Snorkeling'],
        inclusions: ['Overwater Villa', 'All-inclusive Meals', 'Speedboat Transfers'],
        exclusions: ['Flights', 'Premium Drinks'],
        category: ['Luxury', 'Beach', 'Romantic', 'Honeymoon', 'All Inclusive', 'Visa Free'],
        theme: ['International'],
        bestMonths: ['NOV', 'DEC', 'JAN', 'FEB', 'MAR', 'APR'],
        featured: true, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800']
    },
    {
        title: 'European Highlights',
        description: 'A breathtaking 10-day whirlwind tour of Europe covering the romance of Paris, the alps of Switzerland, and the history of Rome.',
        type: 'international',
        region: 'Europe',
        destination: 'Europe',
        country: 'Multiple',
        duration: { days: 10, nights: 9 },
        price: 129999, pricePerPerson: 129999,
        highlights: ['Eiffel Tower', 'Swiss Alps', 'Colosseum Rome', 'Venice Gondola'],
        inclusions: ['3-star Hotels', 'Breakfast', 'Coach Transport', 'City Tours'],
        exclusions: ['Flights', 'Visa', 'Lunches & Dinners'],
        category: ['City', 'Heritage', 'Luxury', 'Romantic'],
        theme: ['International'],
        bestMonths: ['MAY', 'JUN', 'JUL', 'AUG', 'SEP'],
        featured: true, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1491557345352-5929e343eb89?w=800']
    },
    {
        title: 'Classic Vietnam',
        description: 'Traverse the length of Vietnam from the historic streets of Hanoi, cruising Halong Bay, to the bustling energy of Ho Chi Minh City.',
        type: 'international',
        region: 'Asia',
        destination: 'Vietnam',
        country: 'Vietnam',
        duration: { days: 8, nights: 7 },
        price: 54500, pricePerPerson: 54500,
        highlights: ['Halong Bay Cruise', 'Hoi An Lantern Town', 'Cu Chi Tunnels'],
        inclusions: ['Hotels', 'Breakfast', 'Domestic Flights', 'Halong Cruise (1 Night)'],
        exclusions: ['Intl Flights', 'Visa'],
        category: ['Heritage', 'Adventure', 'Nature', 'Food'],
        theme: ['International'],
        bestMonths: ['FEB', 'MAR', 'APR', 'AUG', 'SEP', 'OCT'],
        featured: false, hotDeal: true,
        images: ['https://images.unsplash.com/photo-1528127269322-539801943592?w=800']
    },
    {
        title: 'Aussie Adventure - Sydney & Gold Coast',
        description: 'Discover the land Down Under! See the iconic Sydney Opera House and hit the thrilling theme parks and beaches on the Gold Coast.',
        type: 'international',
        region: 'Australia',
        destination: 'Australia',
        country: 'Australia',
        duration: { days: 7, nights: 6 },
        price: 95000, pricePerPerson: 95000,
        highlights: ['Sydney Opera House', 'Bondi Beach', 'Warner Bros Movie World'],
        inclusions: ['4-star Hotels', 'Breakfast', 'Theme Park Ticket', 'Sydney City Tour'],
        exclusions: ['Flights', 'Visa', 'Meals'],
        category: ['Adventure', 'Family', 'Beach', 'Theme Park'],
        theme: ['International'],
        bestMonths: ['SEP', 'OCT', 'NOV', 'DEC', 'JAN', 'FEB'],
        featured: true, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=800']
    },
    {
        title: 'Swiss Alps & Paris Delights',
        description: 'A focused romantic journey blending the spectacular mountain vistas of Mount Titlis in Switzerland with the timeless charm of Paris.',
        type: 'international',
        region: 'Europe',
        destination: 'Switzerland & France',
        country: 'Multiple',
        duration: { days: 7, nights: 6 },
        price: 115000, pricePerPerson: 115000,
        highlights: ['Mount Titlis Cable Car', 'Lucerne Lake', 'Seine River Cruise', 'Eiffel Tower'],
        inclusions: ['Hotels', 'Breakfast', 'TGV Train', 'Excursion Tickets'],
        exclusions: ['Flights', 'Visa', 'City Taxes'],
        category: ['Honeymoon', 'Romantic', 'Nature'],
        theme: ['International'],
        bestMonths: ['APR', 'MAY', 'JUN', 'SEP', 'OCT'],
        featured: false, hotDeal: true,
        images: ['https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800']
    },
    {
        title: 'South African Safari & Cape Town',
        description: 'Track the Big Five in Kruger National Park and gaze at the stunning coastal views from Table Mountain in cosmopolitan Cape Town.',
        type: 'international',
        region: 'Africa',
        destination: 'South Africa',
        country: 'South Africa',
        duration: { days: 9, nights: 8 },
        price: 135000, pricePerPerson: 135000,
        highlights: ['Kruger Safari', 'Table Mountain', 'Cape of Good Hope', 'Penguin Colony'],
        inclusions: ['Hotel & Lodge Stay', 'Breakfast & Safari Meals', 'Game Drives'],
        exclusions: ['Intl Flights', 'Visa'],
        category: ['Wildlife', 'Adventure', 'Nature'],
        theme: ['International'],
        bestMonths: ['MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT'],
        featured: true, hotDeal: false,
        images: ['https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800']
    }
];

const run = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/travelweb');
        console.log('Connected to MongoDB');
        await Package.deleteMany({});
        const now = new Date();
        const validTo = new Date(now.getTime() + 365 * 86400000);
        await Package.insertMany(packages.map(p => ({ ...p, isActive: true, validFrom: now, validTo })));
        console.log(`Seeded ${packages.length} holiday packages.`);
    } catch (e) { console.error(e); process.exit(1); }
    finally { await mongoose.disconnect(); process.exit(0); }
};
run();
